#!/usr/bin/env bash

print_info() {
    info title
    info underline

    info "os" distro
    info "model" model
    info "shell" shell
    info "wm" wm
    info "term" term
    info "cpu" cpu
    info "ram" memory
	
    info line_break
    info cols
    info line_break

    # info "Packages" packages
    # info "gpu" gpu
}


kernel_shorthand="on"
distro_shorthand="off"
os_arch="off"
uptime_shorthand="tiny"
shell_path="off"
shell_version="off"
speed_type="bios_limit"
speed_shorthand="on"
cpu_shorthand="tiny"
cpu_speed="off"
cpu_cores="off"
cpu_temp="off"
gpu_brand="off"
gpu_type="all"
refresh_rate="off"
gtk_shorthand="off"
gtk2="on"
gtk3="on"
public_ip_host="http://ident.me"
disk_show=('/')
disk_subtitle="mount"
song_shorthand="off"
install_time="on"
install_time_format="24h"
colors=(15 2 2 15 8 4)
bold="off"
underline_enabled="on"
underline_char="-"
block_range=(0 7)
color_blocks="on"
block_width=3
block_height=1
bar_char_elapsed="-"
bar_char_total="-"
bar_border="off"
bar_length=10
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="infobar"
battery_display="off"
disk_display="off"
image_backend="ascii"
image_source="auto"
ascii_distro="nix"
ascii_colors=(distro)
ascii_bold="off"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=3
yoffset=0
xoffset=0
background_color=
scrot="off"
scrot_cmd="auto"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="teknik"
config_version="3.2.0"
