execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set tabstop=2
set ColorColumn=110

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

set laststatus=2

let g:Powerline_symbols= 'fancy'

set makeprg=make\ -C++ ../build\ -j9

filetype plugin on

augroup pencil
	autocmd!
	autocmd FileType markdown,mkd call pencil#init()
	autocmd FileType text call pencil#init()
augroup END

let g:airline_theme='base16'
