#!/bin/bash

source $HOME/.cache/squash/colors

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc edge_gap           35 0 0 0

# Set decoration colors
berryc focus_color         ${BG:1:7}
berryc unfocus_color       ${BG:1:7}
berryc inner_focus_color   ${BBLK:1:7}
berryc inner_unfocus_color ${BLK:1:7}
berryc text_focus_color    ${FG:1:7}
berryc text_unfocus_color  ${WHT:1:7}

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    $BERRY_FONT
