#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config border_width         4
bspc config window_gap           12

bspc config borderless_monocle   false 
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

source "${HOME}/.cache/squash/colors"

bspc config normal_border_color "${BSPWM_NORMAL}"
bspc config focused_border_color "${BSPWM_FOCUSED}"
