#!/bin/sh

source "${HOME}/.cache/squash/colors"

waitron wm_config border_width 5
waitron wm_config color_focused "${TWOBWM_FOCUS:1:7}"
waitron wm_config color_unfocused "${TWOBWM_UNFOCUS:1:7}"
waitron wm_config gap_width all 0
waitron wm_config grid_gap_width 0
waitron wm_config cursor_position middle
waitron wm_config groups_nr 9
waitron wm_config enable_resize_hints false
waitron wm_config enable_sloppy_focus true
waitron wm_config sticky_windows false
waitron wm_config enable_borders true
waitron wm_config enable_last_window_focusing true
waitron wm_config apply_settings true
waitron wm_config replay_click_on_focus true
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
waitron wm_config click_to_focus any

waitron wm_config gap_width top 30
