#!/usr/bin/env bash

# source the colors from colors.sh
source "/home/jlervin/.cache/squash/colors.sh"

# vars
p="  "

desktops() {
	cur=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
	tot=`xprop -root _NET_NUMBER_OF_DESKTOPS | awk '{print $3}'`

	for w in `seq 0 $((cur - 1))`; do line="${line}"; done
	line="${line}"
	for w in `seq $((cur + 2)) $tot`; do line="${line}"; done
	echo $line
}

window() {
	cwindow=$(xdotool "getwindowfocus" "getwindowname" | head -c50)

	if [ "$cwindow" == "Openbox" ] ; then
		echo ""
	elif [ "$(song)" == "" ] ; then
		echo "$a1   $cwindow  "
	else
		echo "$a2   $cwindow  "
	fi
}

song() {
	csong=$(mpc current | head -c50)
	playing=$(mpc status | grep -o 'playing' )

	if [ "$playing" == "playing" ]; then
		echo "   $csong  "
	else [ "$playing" == "" ];
		echo ""
	fi
}

clock() {
	datetime=$(date "+%a %b %d %R")

	echo $datetime
}

weather() {
	cat "/tmp/fweather"
}

network() {
	cnetwork=$(iwgetid -r)

	if [ "$cnetwork" == "" ]; then
		echo $wrn$txt offline
	else
		echo  $cnetwork
	fi
}

sound() {
	#level=$(amixer get Master 2>&1 | awk '/Front Left:/{gsub(/[\[\]]/, "", $5); print $5}')
	level=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))
	muted=$(amixer get Master | grep -o off | tail -n1)

	if [ "$muted" == "off" ]; then
		echo $wrn$txt
	else
		echo  $level
	fi
}

battery() {
    percent=$(cat /sys/class/power_supply/BAT0/capacity)
    power=$(cat /sys/class/power_supply/BAT0/status)

	if [[ $power == "Charging" || $power == "Unknown" ]]; then
		echo -n " $percent%"
	else
		if [ $percent -eq 100 ]; then
			echo -n " $percent%"
		elif [ $percent -gt 80 ] ; then
			echo -n " $percent%"
		elif [ $percent -gt 30 ]; then
			echo -n " $percent%"
		else
			echo -n " $percent%"
		fi
	fi
}


loop() {
	while :; do
		echo "%{l}%{A1:popup.sh "term" "ncmpcpp" "60x20+760+40" &:}%{A3:mpc toggle &:}$a0$p$(desktops)$p$a1$(window)$bg%{c}$p$(clock)$p%{r}$a2$p$(network)$p$a1$p$(sound)$p$a0$p$(battery)$p$bg"
		sleep ".2s"
	done |\

	lemonbar \
			-f '-uw-ttyp0-medium-r-normal-*-12-*-*-*-*-*-*-*' \
	    -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1' \
	    -g "x30" \
	    | bash
}

loop "$@"
