#! /bin/sh

#    __                                          
#   / /_  _________ _      ______ ___  __________
#  / __ \/ ___/ __ \ | /| / / __ `__ \/ ___/ ___/
# / /_/ (__  ) /_/ / |/ |/ / / / / / / /  / /__  
#/_.___/____/ .___/|__/|__/_/ /_/ /_/_/   \___/  
#          /_/                                   

sxhkd &
pbar &
xrdb ~/.Xresources &
bash ~/scripts/res &
bash ~/scripts/end &
nitrogen --set-tiled ~/wallpapers/small_steps.png &
pkill -x xfce4-notify &
dunst /home/jlervin/.config/dunst/dunstrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        5
bspc config window_gap         	0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 30 
bspc config bottom_padding 0 


##Color settings


bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#3b2d26" 
bspc config normal_border_color "#30251f"
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"
bspc config focused_private_border_color "#35BF5C"
bspc config border_width 4 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a docky --focus
