#! /bin/sh

sxhkd &
#polybar middle &
#polybar battery &
#polybar volume &
#polybar bottom &
#polybar cpu &
#polybar temperature &
polybar top &
nitrogen ~/Downloads/681135.jpg --set-auto &

bspc monitor -d I II III IV
bspc monitor HDMI-1 -d  V VI X

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 40
bspc config bottom_padding 20


##Color settings
#bspc config normal_frame_opacity 1.0
#bspc config focused_frame_opacity 0.05
bspc config focused_border_color "3B4246"
bspc config border_width 4
#bspc config normal_border_color "#2B3135"
#bspc config presel_border_color "#8F3724"
#bspc config urgent_border_color "#504339"
#bspc config focused_private_border_color "#35BF5C"
#bspc config border_width 4 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a docky --focus
