#!/bin/bash

bg=#242e32
fg=#c4c4b5
blk=#253034
bblk=#35444b
red=#a66959
grn=#769070
ylw=#ac8d6e
blu=#607a86
mag=#8a757e
cyn=#60867f
wht=#c4c4b5
bred=#a66959
bgrn=#769070
bylw=#ac8d6e
bblu=#607a86
bmag=#8a757e
bcyn=#60867f
bwht=#c4c4b5

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/designrlighter.png
