#!/bin/bash

bg=#2e3738
fg=#aba599
blk=#343c3c
bblk=#485152
red=#9c7f5d
grn=#8e958f
ylw=#b8af97
blu=#828882
mag=#bb9a7f
cyn=#9daba2
wht=#aba599
bred=#9c7f5d
bgrn=#8e958f
bylw=#b8af97
bblu=#828882
bmag=#bb9a7f
bcyn=#9daba2
bwht=#aba599

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/plmbg.png
