#!/bin/bash

bg=#282828
fg=#ebdbb2
blk=#3c3836
bblk=#a89984
red=#cc241d
grn=#98971a
ylw=#d79921
blu=#458588
mag=#b16286
cyn=#689d6a
wht=#fbf1c7
bred=#fb4934
bgrn=#b8bb26
bylw=#fabd2f
bblu=#83a598
bmag=#d3869b
bcyn=#8ec07c
bwht=#fbf1c7

acc0="#d79921"
acc1="#3c3836"
acc2="#3c3836"
acc3="#3c3836"
acc4="#3c3836"

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/alberto-restifo-40088.jpg

