#!/bin/bash

# Credit goes to nxll_ for this colorscheme

bg=#3C4254
fg=#FEDDD0
blk=#4B5269
bblk=#57607A
red=#D8686D
grn=#918EB3
ylw=#EBC6A1
blu=#B84E46
mag=#875F87
cyn=#F77C6C
wht=#FDCBAC
bred=#ED7278
bgrn=#A19EC7
bylw=#FFD7AF
bblu=#CC564E
bmag=#9C6D9C
bcyn=#FF806F
bwht=#FDCBAC

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/yuriy-khimanin-133.jpg
