#!/bin/bash

bg=#222222
blk=#242424
fg=#c2c2c2
bblk=#484848
red=#4d4d4d
grn=#8a8c84
ylw=#c5c5b2
blu=#5d5d5d
mag=#707070
cyn=#898989
wht=#c2c2c2
bred=#4d4d4d
bgrn=#8a8c84
bylw=#c5c5b2
bblu=#5d5d5d
bmag=#707070
bcyn=#898989
bwht=#f1f1f1

obbg=${ylw}
obibg=${fg}
cpubg=${ylw}
winbg=${ylw}
netbg=${ylw}
volbg=${ylw}
batbg=${ylw}
malbg=${ylw}

obfg=${bg}
obifg=${bg}
cpufg=${bg}
winfg=${bg}
netfg=${bg}
volfg=${bg}
batfg=${bg}
malfg=${bg}

acc0="#8a8c84"
acc1="#4d4d4d"
acc2="#4d4d4d"
acc3="#4d4d4d"
acc4="#4d4d4d"

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/alberto-restifo-40088.jpg

