#!/bin/bash

bg=#2f2b2c
fg=#dedede
blk=#302c2c
bblk=#504c4e
red=#5a5a5a
grn=#989898
ylw=#cacaca
blu=#656565
mag=#b1b1b1
cyn=#7f7f7f
wht=#dedede
bred=#da5b2c
bgrn=#989898
bylw=#cacaca
bblu=#656565
bmag=#b1b1b1
bcyn=#7f7f7f
bwht=#FFFFFF

obbg=${ylw}
obibg=${fg}
cpubg=${ylw}
winbg=${ylw}
netbg=${ylw}
volbg=${ylw}
batbg=${ylw}
malbg=${ylw}

obfg=${bg}
obifg=${bg}
cpufg=${bg}
winfg=${bg}
netfg=${bg}
volfg=${bg}
batfg=${bg}
malfg=${bg}

acc0="#8a8c84"
acc1="#4d4d4d"
acc2="#4d4d4d"
acc3="#4d4d4d"
acc4="#4d4d4d"

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/alberto-restifo-40088.jpg

