#!/bin/bash

# Credit goes to dkeg for this colorscheme

bg=#2e384b
blk=#272c34
bblk=#3b434f
fg=#bab7b5
red=#876058
grn=#6f7f71
ylw=#b39580
blu=#546780
mag=#84787d
cyn=#556f86
wht=#bab7b5
bred=#876058
bgrn=#6f7f71
bylw=#b39580
bblu=#546780
bmag=#84787d
bcyn=#556f86
bwht=#dfdedd

main_bg=${bg}
alt_bg=${bblk}
alt_bg_bright=${blu}
main_fg=${fg}
wallpaper=~/wallpapers/skighbg.png
