#!/usr/bin/env bash

source $HOME/.cache/squash/colors
SEP="  "
SEPB="__"
SPC="%{B$bg}%{F$bg}$SEPB%{B-}%{F-}"

# Generate glyphs for Siji using echos
# Seems more consistent to me than copy/pasting
# the characters themselves
glycur=$(echo -e "\ue000")
glyem=$(echo -e "\ue001")
glydate=$(echo -e "\ue015")
glyvol=$(echo -e "\ue050")
glyvoloff=$(echo -e "\ue052")
glybatlow=$(echo -e "\ue035")
glybat=$(echo -e "\ue037")
glybatmax=$(echo -e "\ue09e")
glywlanhigh=$(echo -e "\ue048")
glywlanlow=$(echo -e "\ue047")

# Create formatting colors using color codes
# from cache file
grn="%{B$bg}%{F$grn}"
red="%{B$bg}%{F$red}"
blu="%{B$bg}%{F$blu}"
ylw="%{B$bg}%{F$ylw}"
cyn="%{B$bg}%{F$cyn}"
mag="%{B$bg}%{F$mag}"
wht="%{B$bg}%{F$wht}"
blk="%{B$bg}%{F$blk}"
fg="%{B$bg}%{F$fg}"


# Bar contents
content() 
{
    # Get current workspaces
    workspaces()
    {
       cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
       total=5

       empty=$(echo -e "\ue000")

       seq=""

       for ((i=0; i<$cur && i<$(($total-1)); i++)); do seq+="${fg}${glyem}${clr}"; done
       seq+="${ylw}${glycur}${clr}"
       for ((i=$(($cur+1)); i<$total; i++)); do seq+="${fg}${glyem}${clr}"; done

       echo "$seq"
    }

    # Clock
    date-time() 
    {
        clock="${fg}$(date +'%a %d %I:%M')${clr}"
        label="${ylw}${glydate}${clr}"
        echo "${label}${SEP}${clock}"
    }

    # Volume 0-100
    # Glyph will change when volume is muted
    volume() 
    {
        vol="${fg}$(amixer get Master|awk 'NR==5 {print $4}'|cut -d '%' -f1 | cut -d '[' -f2)${clr}"
        label="${red}${glyvol}${clr}"

        echo "${label}${SEP}${vol}"
    }

    # Battery 0-100
    # Battery considered charged at 98%
    # Glyph changes below 20 %
    battery()
    {
        cap="${fg}$(cat /sys/class/power_supply/BAT0/capacity)${clr}"
        label="${grn}${glybat}${clr}"

        echo "${label}${SEP}${cap}"
    }

    # Get SSID using iwgetid
    # If iwgetid is not found, then DISCONNECTED will be displayed
    wireless()
    {
        wifi=$(iwgetid -r)

        if [[ -z $wifi ]]; then
            wifi="DISCONNECTED"
        fi

        wifi="${fg}${wifi}${clr}"
        label="${red}${glywlanhigh}${clr}"

        echo "${label}${SEP}${wifi}"
    }


    # Bar contents left/right
    left="$(workspaces)"
    center=
    right="$(volume)${SPC}$(battery)${SPC}$(wireless)${SPC}$(date-time)${SCP}"

    output="$left%{c}$center%{r}$right"
    echo -n "$output"
}

content

# Formatting options
fonts="-f -uw-ttyp0-medium-r-normal-*-14-*-*-*-*-*-*-* -f -*-siji-*"
width=1920
height=30
# x - y offsets
xoff=0
yoff=0
# Border width
# Only works with patched lemonbar:w
brdr=0
# Border color
brdrc=${bg}
# Bar background color
bbg=${bg}
# Bar foreground color
bfg=${fg}

# Final output formatting
options="-d ${fonts} -g ${width}x${height}+${xoff}+${yoff} -B ${bbg} -F ${bfg}" 

# Main loop
while true; do
    echo $(content)
    sleep .5
done | lemonbar ${options}
