#!/bin/sh

# This is needed for notify-send
# to work right
export DISPLAY=:0

cap=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $cap -le 20 ]; then
    notify-send -u critical "Battery low"
elif [ $cap -ge 99 ]; then
    notify-send -u normal "Battery charged"
fi

echo "SENT"
