#!/bin/sh

# This is needed for notify-send
# to work right
export DISPLAY=:0

cap=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $cap -le 20 ]; then
    notify-send -u critical "BAT LOW"
elif [ $cap -ge 99 ]; then
    notify-send -u normal "BAT CHARGED"
else
    notify-send -u normal "BAT @ $cap"
fi

echo "SENT"
