#!/usr/bin/env bash
#
# -- infobar2: minimal block-style bar for use with lemonbar
# -- Author  : Joshua L Ervin @ Unversity of Washington
# -- Contant : jlervin@posteo.net

source "${HOME}/.cache/squash/colors"
SEP="  "
SEP2="    "
SEPB="__"
SPC="%{B$BG}%{F$BG}$SEPB%{B-}%{F-}"

# Generate glyphs for Siji using echos
# Seems more consistent to me than copy/pasting
# the characters themselves
GLYCUR=$(echo -e "\ue000")
GLYEM=$(echo -e "\ue001")
GLYDATE=$(echo -e "\ue015")
GLYVOL=$(echo -e "\ue050")
GLYVOLoff=$(echo -e "\ue052")
GLYBATLOW=$(echo -e "\ue035")
GLYBAT=$(echo -e "\ue037")
GLYBATMAX=$(echo -e "\ue09e")
GLYWLANHIGH=$(echo -e "\ue048")
GLYWLANLOW=$(echo -e "\ue047")

# Status colors w/ formatting
PANIC="%{F$MAG}%{B$BG}${SEP}"
ALERT="%{F$RED}%{B$BG}${SEP}"
WARN="%{F$YLW}%{B$BG}${SEP}"
GOOD="%{F$GRN}%{B$BG}${SEP}"
PLAIN="%{F$WHT}%{B$BG}${SEP}"
GEN="%{F$FG}%{B$BG}${SEP}"
EMPTY="%{F$FG}%{B$BG}${SEP}"
BLACK="%{F$FG}%{B$BG}${SEP}"
#FULL="%{F$RED}%{B$BLK}${SEP}"
FULL="%{F$ACC}%{B$BG}${SEP}"
CLR="${SEP}%{B-}${F-}"

if [ ! -z ${LMNBAR_DARK} ]; then
    PANIC="%{F$MAG}%{B$BG}${SEP}"
    ALERT="%{F$RED}%{B$BG}${SEP}"
    WARN="%{F$YLW}%{B$BG}${SEP}"
    GOOD="%{F$GRN}%{B$BG}${SEP}"
    PLAIN="%{F$WHT}%{B$BG}${SEP}"
    GEN="%{F$FG}%{B$BG}${SEP}"
    EMPTY="%{F$FG}%{B$BG}${SEP}"
    BLACK="%{F$FG}%{B$BG}${SEP}"
    #FULL="%{F$RED}%{B$LMNBAR_DARKER}${SEP}"
    FULL="%{F$ACC}%{B$BG}${SEP}"
fi

# Bar contents
function content() 
{
    # Get current workspaces
    # Displays the active workspace using a 0 index
    # Notes:
    #   Requires xprop to get current desktop
    #   For windochef to function properly, 
    #   windows must be assigned to groups
    function workspaces() {
        local cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
        local total=5
        local seq=""

        for ((i=0; i<${cur} && i<$((${total}-1)); i++)); do 
            #seq+="${GEN}${i}"
            seq+="${EMPTY}${i}"
        done

        #seq+="${SEP}${BLACK}${cur}${SEP}"
        #seq+="${SEP}%{!u$GRN}${FULL}${cur}${SEP}%{-u}"
        seq+="${FULL}${cur}"

        for ((i=$((${cur}+1)); i<$total; i++)); do
            #seq+="${GEN}${i}"
            seq+="${EMPTY}${i}"
        done

        echo "${seq}${CLR}"
    }

    # Clock function gets current time and displays
    # Day of week, date, and time
    function date-time() 
    {
        local clock="$(date +'%a %d %I:%M')"
        echo "${GEN}${GLYDATE}${SEP}${BLACK}${clock}${CLR}"
    }

    # Volume 0-100
    # Glyph will change when volume is muted
    # Notes:
    #   Requires amixer to get volume
    function volume() 
    {
        local vol="$(amixer get Master|awk 'NR==5 {print $4}'|cut -d '%' -f1 | cut -d '[' -f2)"
        local mut="$(amixer get Master| awk 'NR==5 {print $6}')"

        if [[ ${mut} = "[off]" ]]; then
            echo "${ALERT}${GLYVOL}${SEP}${BLACK}${vol}${CLR}"
        elif [[ ${vol} = 0 ]]; then
            echo "${WARN}${GLYVOL}${SEP}${BLACK}${vol}${CLR}"
        else
            echo "${GOOD}${GLYVOL}${SEP}${BLACK}${vol}${CLR}"
        fi
    }

    # Battery 0-100
    # Battery considered charged at 98%
    # Glyph changes below 20 %
    function battery() 
    {
        local cap="$(cat /sys/class/power_supply/BAT0/capacity)"
        local stat="$(cat /sys/class/power_supply/BAT0/status)"

        if [[ ${cap} -ge 98 || ${stat} = "Charging" ]]; then
            echo "${GOOD}${GLYBATMAX}${SEP}${BLACK}${cap}${CLR}"
        elif [[ ${cap} -ge 50 ]]; then
            echo "${WARN}${GLYBAT}${SEP}${BLACK}${cap}${CLR}"
        else 
            echo "${ALERT}${GLYBATLOW}${SEP}${BLACK}${cap}${CLR}"
        fi
    }

    # Get SSID using iwgetid
    # If iwgetid is not found, then DISCONNECTED will be displayed
    function wireless() 
    {
        local wifi=$(iwgetid -r)

        if [[ -z $wifi ]]; then
            local wifi="DISCONNECTED"
            echo "${ALERT}${GLYWLANLOW}${SEP}${BLACK}${wifi}${CLR}"
        else
            echo "${GOOD}${GLYWLANHIGH}${SEP}${BLACK}${wifi}${CLR}"
        fi
    }

    # Bar contents left/right
    local left="$(workspaces)"
    local center=
    local right="$(wireless)"${SEP2}"$(battery)"$SEP2"$(volume)"$SEP2"$(date-time)"
    local output="${left}%{c}${center}%{r}${right}"

    echo -n "${output}"
}

content

# Formatting options
fonts="-f -uw-ttyp0-medium-r-normal-*-14-*-*-*-*-*-*-* -f -*-siji-*"
width=1910
height=20
# x - y offsets
xoff=0
yoff=0
# Border width
# Only works with patched lemonbar
brdr=5
# Border color
# Only works with patched lemonbar
brdrc=${BG}
# Bar background color
#bbg=${wht}
# Non-transparent
bbg=${BG}
# Transparent, requires compton
#bbg=#00000000
#Bar foreground color
bfg=${FG}

# Final output formatting
options="-d ${fonts} -g ${width}x${height}+${xoff}+${yoff} -B ${bbg} -F ${bfg} -r 5 -R ${brdrc}" 

# Main loop
while true; do
    echo $(content)
    sleep .5
done | lemonbar ${options} | sh > /dev/null 2>&1
