#!/usr/bin/env bash

source $HOME/.cache/squash/colors
SEP="  "
SEPL="%{B$bg}%{F$bg}"--"%{F-}%{B-}"

# Get glyphs from siji
# Using queries is easier than c/p
glydate=$(echo -e "\ue015")
glyvol=$(echo -e "\ue050")
glyvoloff=$(echo -e "\ue052")
glybatlow=$(echo -e "\ue035")
glybat=$(echo -e "\ue037")
glybatmax=$(echo -e "\ue09e")
glywlanhigh=$(echo -e "\ue048")
glywlanlow=$(echo -e "\ue047")

# Create template for colors

clr="%{B-}%{F-}"

content() 
{
    # Get current workspaces
    workspaces()
    {
       cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
       echo "${SEPL}%{B$bg}%{F$fg}${cur}%{F-}%{B-}${SEPL}"
    }

    # Clock
    date-time() 
    {
        clock="$(date +'%a %d %I:%M')"
        label="$glydate"
        echo "%{B$#ffffff}%{F$blk}${clock}%{B-}%{F-}"
    }

    # Volume 0-100
    # Glyph will change when volume is muted
    volume() 
    {
        vol=$(amixer get Master|awk 'NR==5 {print $4}'|cut -d '%' -f1 | cut -d '[' -f2)
        echo "%{B#ffffff}%{F$blk}" - "${vol}%{B-}%{F-}"
    }

    # Bar contents left/right
    left="$(workspaces)${SEP}$(date-time)$(volume)"
    center=""
    right="" 
    output="$left%{c}$center%{r}$right"
    echo -n "$output"
}

content

# Formatting options
fonts="-o 1 -f -uw-ttyp0-medium-r-normal-*-14-*-*-*-*-*-*-* -o -0.5 -f -wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"
width=170
height=30
#offx=885
offx=20
offy=10
brdr=0
brdrc=${bg}
bbg=#ffffff
bfg=${blk}

# Final output formatting
options="-d ${fonts} -g ${width}x${height}+${offx}+${offy} -r ${brdr} -R ${brdrc} -B ${bbg} -F ${bfg} -b"

while true; do
    echo $(content)
    sleep .5 
done | lemonbar ${options}
