#!/usr/bin/env bash

TOGGLE_FILE="/tmp/toggle"

# Create file if it doesn't exist
if [ ! -f $TOGGLE_FILE ]; then
    touch $TOGGLE_FILE
    echo "1" > $TOGGLE_FILE
fi

CUR="$(head -n 1 $TOGGLE_FILE)"

if [ $CUR -eq "0" ]; then
    echo "1" > $TOGGLE_FILE
    teny &
else
    echo "0" > $TOGGLE_FILE
    pkill -x lemonbar
fi
