#!/bin/sh

raw_colors="$(grep ":\s*#" "$1" | sed 's/\*\.//g')"

IFS=$'\n'
for line in $raw_colors; do
	key="$(echo $line | awk '{print $1}' | tr -d ':')"
	color="$(echo $line | awk '{print $2}')"

	echo "$key $color"
done
